<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="8" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="MainSuite" duration-ms="626" started-at="2015-05-22T13:59:14Z" finished-at="2015-05-22T13:59:15Z">
    <groups>
    </groups>
    <test name="T1" duration-ms="626" started-at="2015-05-22T13:59:14Z" finished-at="2015-05-22T13:59:15Z">
      <class name="com.rc.wefunit.testengine.TestEngineTest">
        <test-method status="PASS" signature="method_executeTests_tests_reports_failed_tests_arrays_size_should_be_equal_to_total_failed_tests()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_executeTests_tests_reports_failed_tests_arrays_size_should_be_equal_to_total_failed_tests" duration-ms="317" started-at="2015-05-22T18:59:14Z" finished-at="2015-05-22T18:59:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_executeTests_tests_reports_failed_tests_arrays_size_should_be_equal_to_total_failed_tests -->
        <test-method status="PASS" signature="method_executeTests_total_executed_tests_should_equal_to_total_no_of_tests_present()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_executeTests_total_executed_tests_should_equal_to_total_no_of_tests_present" duration-ms="56" started-at="2015-05-22T18:59:14Z" finished-at="2015-05-22T18:59:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_executeTests_total_executed_tests_should_equal_to_total_no_of_tests_present -->
        <test-method status="PASS" signature="method_executeTests_total_passed_tests_should_be_equal_to_total_tests_minus_total_failed_tests()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_executeTests_total_passed_tests_should_be_equal_to_total_tests_minus_total_failed_tests" duration-ms="44" started-at="2015-05-22T18:59:14Z" finished-at="2015-05-22T18:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_executeTests_total_passed_tests_should_be_equal_to_total_tests_minus_total_failed_tests -->
        <test-method status="PASS" signature="method_executeTests_total_test_for_explicitly_failed_tests()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_executeTests_total_test_for_explicitly_failed_tests" duration-ms="48" started-at="2015-05-22T18:59:15Z" finished-at="2015-05-22T18:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_executeTests_total_test_for_explicitly_failed_tests -->
        <test-method status="PASS" signature="method_getTestScores_returned_map_must_contain_report_document()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_getTestScores_returned_map_must_contain_report_document" duration-ms="0" started-at="2015-05-22T18:59:15Z" finished-at="2015-05-22T18:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_getTestScores_returned_map_must_contain_report_document -->
        <test-method status="PASS" signature="method_getTestScores_returned_map_must_contain_score_document()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_getTestScores_returned_map_must_contain_score_document" duration-ms="0" started-at="2015-05-22T18:59:15Z" finished-at="2015-05-22T18:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_getTestScores_returned_map_must_contain_score_document -->
        <test-method status="PASS" signature="method_getTestScores_returned_map_validating_failed_test_objects_structures_inside_report_failed_array(java.lang.String)[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_getTestScores_returned_map_validating_failed_test_objects_structures_inside_report_failed_array" duration-ms="1" started-at="2015-05-22T18:59:15Z" finished-at="2015-05-22T18:59:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_getTestScores_returned_map_validating_failed_test_objects_structures_inside_report_failed_array -->
        <test-method status="FAIL" signature="method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map()[pri:0, instance:com.rc.wefunit.testengine.TestEngineTest@523884b2]" name="method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map" duration-ms="83" started-at="2015-05-22T18:59:15Z" finished-at="2015-05-22T18:59:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [9] but found [22]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [9] but found [22]
	at com.rc.wefunit.testengine.TestEngineTest.method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map(TestEngineTest.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method_getTestScores_validating_the_test_classes_names_inside_report_section_of_test_scoring_map -->
      </class> <!-- com.rc.wefunit.testengine.TestEngineTest -->
    </test> <!-- T1 -->
  </suite> <!-- MainSuite -->
</testng-results>
