<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ubuntu" name="com.rc.wefunit.testengine.TestEngineTest" tests="4" failures="0" timestamp="20 May 2015 16:36:08 GMT" time="0.218" errors="1">
  <testcase name="method_getTestScores_returned_map_must_contain_score_document" time="0.001" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_getTestScores_returned_map_validating_failed_test_objects_structures_inside_report_failed_array" time="0.139" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="method_getTestScores_returned_map_must_contain_report_document" time="0.075" classname="com.rc.wefunit.testengine.TestEngineTest"/>
  <testcase name="t1" time="0.003" classname="com.rc.wefunit.testengine.TestEngineTest">
    <error type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.rc.wefunit.testengine.TestEngineTest.t1(TestEngineTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- t1 -->
</testsuite> <!-- com.rc.wefunit.testengine.TestEngineTest -->
